spring.application.name=Gojo

spring.datasource.url= jdbc:postgresql://localhost:5432/Gojo

spring.datasource.username=postgres

spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=user
spring.security.user.password=password

jwt.secret=my-secret-key-for-gojo-satoru-ecommerce-website-void
jwt.expiration=3600000